explodingquests/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from django.views.generic import TemplateView
from profiles.views import ContactUsFormView
from quests.views import (
    QuestListView,
    get_user_settings,
    password_change_page_view,
    account_inactive_redux,
    email_verification_redux,
)


urlpatterns = [
    url(r'^$', QuestListView.as_view(), name='homepage'),
    url(r'^quests/', include('quests.urls', namespace='quests')),
    url(r'^accounts/password/change/$', password_change_page_view, name='account_change_password'),
    url(r'^accounts/inactive/$', account_inactive_redux, name='account_inactive'),
    url(r'^accounts/confirm-email/$', email_verification_redux, name='account_email_verification_sent'),
    url(r'^accounts/settings/$', get_user_settings, name='user_settings'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^dashboards/', include('profiles.urls', namespace='dashboard')),
    url(r'^contact/$', ContactUsFormView.as_view(), name='contact_us'),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

quests/urls.py
from django.conf.urls import url

from .views import (
    QuestListView, QuestDetailView,
    CreateQuest, DeleteQuestView,
    UpdateQuestView,
    get_selected_user_list,
    edit_quest_images,
    delete_quest_images,
    interested_users_list,
    get_selected_user_profile,
    MessageCreateView,
    DiffuseToggle,
)

urlpatterns = [
    # url(r'^$', QuestListView.as_view(), name='homepage'),
    url(r'^create/$', CreateQuest.as_view(), name='create_quest'),
    url(r'^(?P<slug>[\w-]+)/$', QuestDetailView.as_view(), name='quest_detail'),
    url(r'^(?P<slug>[\w-]+)/images/$', edit_quest_images, name='edit_quest_images'),
    url(r'^delete/(?P<id>[\w-]+)/$', delete_quest_images, name='delete_quest_images'),
    url(r'^(?P<slug>[\w-]+)/defuse/$', DiffuseToggle.as_view(), name='diffuse'),
    url(r'^(?P<slug>[\w-]+)/interested/$', interested_users_list, name='interested_users'),
    url(r'^(?P<slug>[\w-]+)/interested/(?P<username>[a-zA-Z0-9]+)/$',
        get_selected_user_profile, name='selected_user_profile'),
    url(r'^(?P<slug>[\w-]+)/interested/(?P<username>[a-zA-Z0-9]+)/send_msg/$',
        MessageCreateView.as_view(), name='send_message'),
    url(r'^(?P<slug>[\w-]+)/update/$', UpdateQuestView.as_view(), name='update_quest'),
    url(r'^(?P<slug>[\w-]+)/delete/$', DeleteQuestView.as_view(), name='delete_quest'),
    url(r'^(?P<username>[a-zA-Z0-9]+)/quest_list/$', get_selected_user_list, name='selected_user_list'),
]

quests/models.py
import os

from datetime import time, timedelta

from django.db import models
from django.conf import settings
# from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.text import slugify


from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver

from PIL import Image

from .utils import unique_slug_generator
# Create your models here.


def get_image_path(instance, filename):
    # filename, extension = filename.split(".")
    # new_filename = "%s.%s" %(filename+"_thumbnail", extension)
    return '/'.join(['quest_images', instance.quest.slug, filename])


def get_profile_thumbnail_path(instance, filename):
    return '/'.join(['profile_thumbnail', instance.user.username, filename])


class TimeStampModel(models.Model):

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    explosion_datetime = models.DateTimeField(default=timezone.now()+timedelta(days=1))

    class Meta:
        abstract = True


class RewardModel(models.Model):
    REWARD_TYPE = (
        ('MonetaryH', 'Monetary (Hourly)'),
        ('MonetaryF', 'Monetary (Flat)'),
        ('Non-monetary', 'Non-monetary'),
        ('Voluntary', 'Voluntary'),
    )

    MON_REWARD_RATE = (
        ('Hourly', 'Hourly'),
        ('Flat', 'Flat'),
    )

    reward_type = models.CharField(
        max_length=15,
        choices=REWARD_TYPE,
        default=REWARD_TYPE[0][0])
    mon_reward = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,)
    non_mon_rewards = models.CharField(
        max_length=255,
        null=True,
        blank=True,)

    class Meta:
        abstract = True


class UserProfileImage(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name='profile_thumbnail',
        primary_key=True,
        on_delete=models.CASCADE,)
    preferred_name = models.CharField(max_length=200, null=True, blank=True)
    profile_thumbnail = models.ImageField(
        upload_to=get_profile_thumbnail_path,
        null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.profile_thumbnail:
            profile_thumbnail = Image.open(self.profile_thumbnail)
            i_width, i_height = profile_thumbnail.size
            max_size = (200, 200)

            if i_width > 200:
                profile_thumbnail.thumbnail(max_size, Image.ANTIALIAS)
                profile_thumbnail.save(self.profile_thumbnail.path, 'PNG')

    def __str__(self):
        return self.user.username + ' profile_img'

    def image_url(self):
        if self.profile_thumbnail and hasattr(self.profile_thumbnail, 'url'):
            return self.profile_thumbnail.url
        else:
            return '/static/image/default_profile.jpg'

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    user = instance
    if created:
        profile = UserProfileImage(user=user)
        profile.save()


class Quest(TimeStampModel, RewardModel):
    user = models.ForeignKey(
            settings.AUTH_USER_MODEL,
            related_name='quests',
            on_delete=models.CASCADE
          )
    interested_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name='interested_users')
    title = models.CharField(max_length=255)
    description = models.TextField()
    location = models.TextField(null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    @property
    def past_explosion_date(self):
        if timezone.now() > self.explosion_date:
            return True
        return False

    class Meta:
        ordering = ['-date_created']    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('quests:quest_detail', kwargs={"slug": self.slug})


@receiver(pre_save, sender=Quest)
def quest_pre_save_receiver(sender, instance, *args, **kwargs):
    print('saving...')
    print(instance.date_created)
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


class Upload(models.Model):
    quest = models.ForeignKey(
        Quest,
        related_name='uploads',
        on_delete=models.CASCADE)
    quest_images = models.ImageField(upload_to=get_image_path)

quests/views.py
from allauth.account.models import EmailAddress
from allauth.account.views import (
    PasswordChangeView, AccountInactiveView,
    EmailVerificationSentView, PasswordResetView, )

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.shortcuts import (
    render, Http404,
    get_object_or_404,
    get_list_or_404,
    HttpResponse,
    redirect,
)
from django.utils import timezone
from django.views.generic import (
    TemplateView, ListView, DetailView,
    RedirectView,
)
from django.views.generic.edit import (
    CreateView, DeleteView, UpdateView,
)

from profiles.models import WorkExperience, Education, DefuseMessage
from profiles.forms import SendMessageForm

from .forms import QuestForm, QuestImageForm, ProfileImageForm
from .models import Quest, UserProfileImage, Upload
from .mixins import RightfulOwnerOfQuestMixin, SendingPermissionMixin

# Create your views here.


@login_required
def get_user_settings(request):
    """go to user settings"""
    profile_user = get_object_or_404(User, username=request.user.username)
    user_profile = UserProfileImage.objects.get(user=profile_user)
    verified = get_object_or_404(EmailAddress, user=request.user, primary=True)

    if request.user != user_profile.user:
        raise Http404

    form_class = ProfileImageForm

    if request.method == "POST":
        form = form_class(
            data=request.POST,
            files=request.FILES,
            instance=user_profile)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = profile_user
            obj.profile_thumbnail = form.cleaned_data['profile_thumbnail']
            obj.save()

        return redirect('user_settings')

    else:
        form = form_class(instance=user_profile)

    context = {
        'profile_user': profile_user,
        'user_profile': user_profile,
        'verification': verified,
        'profile_img_form': form,
    }
    return render(request, 'account/user_settings.html', context)


def get_selected_user_list(request, username):
    """get quests posted by this user"""
    user = get_object_or_404(User, username=username)
    profile = UserProfileImage.objects.get(user=user) 
    verified = get_object_or_404(EmailAddress, user=user, primary="True")

    user_quests_list = ''
    try:
        user_quests_list = get_list_or_404(Quest, user=user, explosion_datetime__gte=timezone.now())
    except ObjectDoesNotExist:
        pass

    context = {
        'user': user,
        'profile': profile,
        'user_quests_list': user_quests_list,
        'verified': verified,
    }

    template = 'quests/selected_user_list.html'
    return render(request, template, context)


class PasswordChangePageView(PasswordChangeView):
    @property
    def success_url(self):
        return reverse_lazy("user_settings")

password_change_page_view = login_required(PasswordChangePageView.as_view())


class AccountInactiveViewRedux(LoginRequiredMixin, AccountInactiveView):
    @property
    def template_name(self):
        if self.request.user.is_active:
            raise Http404
        return 'account/account_inactive.html'

account_inactive_redux = login_required(AccountInactiveViewRedux.as_view())


class EmailVerificationSentViewRedux(LoginRequiredMixin, EmailVerificationSentView):
    @property
    def template_name(self):
        raise Http404

email_verification_redux = login_required(EmailVerificationSentViewRedux.as_view())


@login_required
def edit_quest_images(request, slug):
    """add quest image"""
    quest = get_object_or_404(Quest, slug=slug)

    if quest.user != request.user:
        raise Http404
    
    form_class = QuestImageForm

    if request.method == "POST":
        form = form_class(
            data=request.POST,
            files=request.FILES,
            instance=quest)
        
        files = request.FILES.getlist('quest_images')

        if form.is_valid():
            for f in files:
                Upload.objects.create(
                    quest=quest,
                    quest_images=f,)
        return redirect('quests:quest_detail', slug=slug)

    else:
        form = form_class(instance=quest)

    uploads = quest.uploads.all()

    context = {
        'quest': quest,
        'image_form': form,
        'uploads': uploads,
    }

    return render(request, 'quests/edit_quest_images.html', context)


@login_required
def delete_quest_images(request, id):
    """delete quest image"""
    upload = get_object_or_404(Upload, id=id)

    if request.user != upload.quest.user:
        raise Http404

    upload.delete()

    return redirect('quests:edit_quest_images', slug=upload.quest.slug)


@login_required
def interested_users_list(request, slug):
    """go to defuse list for a particular quest"""
    selected_quest = get_object_or_404(Quest, slug=slug)
    interested_users = selected_quest.interested_users.all()

    if request.user != selected_quest.user:
        raise Http404

    context = {
        'interested_users': interested_users,
        'selected_quest': selected_quest,
    }
    return render(request, 'quests/interested_users.html', context)


@login_required
def get_selected_user_profile(request, slug, username):
    """go to a particular user profile page who pressed defuse for this quest"""
    user = get_object_or_404(User, username=username)
    quest = get_object_or_404(Quest, slug=slug)
    profile_img = UserProfileImage.objects.get(user=user)

    experience = ''

    if request.user != quest.user:
        raise Http404
    else:
        if user not in quest.interested_users.all():
            raise Http404

    try:
        email = get_object_or_404(EmailAddress, user=user, primary=True)
        experience = get_list_or_404(WorkExperience, user=user)
    except:
        pass

    context = {
        'user': user,
        'email': email,
        'experiences': experience,
        'profile_img': profile_img,
        'quest': quest,
    }

    template = 'quests/selected_user_profile.html'
    return render(request, template, context)


class MessageCreateView(LoginRequiredMixin, SendingPermissionMixin, CreateView):
    """creating messages"""
    model = DefuseMessage
    form_class = SendMessageForm
    template_name = 'quests/send_message_form.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        receiver = get_object_or_404(User, username=self.kwargs['username']) 
        context['quest'] = get_object_or_404(Quest, slug=self.kwargs['slug'])
        context['sender'] = get_object_or_404(User, username=self.request.user.username)
        context['receiver_email'] = get_object_or_404(EmailAddress, user=receiver)
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.sender = self.request.user
        self.object.receiver = User.objects.get(username=self.kwargs['username'])
        self.object.related_quest = Quest.objects.get(slug=self.kwargs['slug'])
        self.object.parent = None
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("quests:interested_users", kwargs={'slug': self.kwargs['slug']})


class DiffuseToggle(LoginRequiredMixin, RedirectView):
    """for taking care of logics of pressing defuse"""
    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Quest, slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        request = self.request
        if user.is_authenticated():
            if user not in obj.interested_users.all():
                if user != obj.user:
                    messages.success(
                        request,
                        'Diffuse message successfully sent. The quest creator can now access your profile info.',
                        extra_tags='diffuse-message')
                    obj.interested_users.add(user)
                else:
                    pass
            else:
                if user != obj.user:
                    messages.success(
                        request,
                        'Diffuse message retracted. Your profile info will now be inaccessible to the quest creator.',
                        extra_tags='diffuse-message')
                    obj.interested_users.remove(user)
                else:
                    pass
        return url_


class QuestListView(ListView):
    """Get the total list of quests"""
    template_name = "index.html"
    context_object_name = 'quest_list'
    model = Quest

    def get_queryset(self):
        still_ticking = Quest.objects.all().exclude(explosion_datetime__lte=timezone.now())
        query = self.request.GET.get('q')
        if query:
            results = still_ticking.filter(
                Q(title__icontains=query) | Q(description__icontains=query))
            return results
        else:
            return still_ticking


class QuestDetailView(DetailView):
    """go to detail page of a particular quest"""
    template_name = 'quests/quest_detail.html'
    context_object_name = 'quest'
    model = Quest

    def get_context_data(self, *args, **kwargs):
        context = super(QuestDetailView, self).get_context_data(*args, **kwargs)
        selected_quest = get_object_or_404(Quest, slug=self.kwargs['slug'])
        user = get_object_or_404(User, quests__slug=self.kwargs['slug'])
        context['profile_picture'] = UserProfileImage.objects.get(user=user)
        context['uploaded_images'] = selected_quest.uploads.all()

templates/quests/edit_quest_images.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - {{ quest.title }}
{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    <link rel='stylesheet' type='text/css' href="{% static 'css/quest_image.css' %}">
{% endblock stylesheets %}

{% block content %}
<div class='container'>
    <div class='row'>
        <div class='col-md-8'>
            <div class='thumbnail justify-center upload-thumbnail'>
                <form role="form" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ image_form.as_p }}
                    <label for='id_quest_images'>
                        <img id='uploaded_img' src="{% static 'image/upload.png' %}"/>
                    </label>
                    <p class='h5'>Click to select an image to upload</p>
                    <div class='justify-right'>
                        <input class='btn btn-primary' type="submit" value="Submit" />
                    </div>
                </form>
            </div>
        </div>
        <div class='col-md-4'>
            <div class='thumbnail justify-center'>
                <p class='h5'>Current Images</p>
                <hr/>
                {% for upload in uploads %}
                    <img class='already-uploaded' src="{{ upload.quest_images.url }}"/>
                    <a class='btn btn-danger' href="{% url 'quests:delete_quest_images' id=upload.id %}">Delete</a>
                {% empty %}
                    <p class='justify-center'>No image currently attached to the quest.</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    <script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
    
            reader.onload = function (e) {
                $('#uploaded_img').attr('src', e.target.result);
            }
    
            reader.readAsDataURL(input.files[0]);
        }
    };

    $("#id_quest_images").change(function(){
        readURL(this);
    });
    </script>
{% endblock javascript %}

templates/quests/interested_users.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block stylesheets %}
    {{ block.super }}
    <link rel='stylesheet' type='text/css' href="{% static 'css/interested_users.css' %}">
{% endblock stylesheets %}

{% block content %}
    <div class='container'>
        <div class='row'>
            {% if request.user == selected_quest.user %}
            <div class='col-md-12'>
                <div class='thumbnail interested-users-heading'>
                    <div class='justify-center'>
                        <span class='interested-users-quest-title'>
                            - {{ selected_quest.title|title }} -
                        </span>
                        <p>Defuse List</p>
                    </div>
                </div>
            </div>
            {% for user in interested_users %}
                <a href="{% url 'quests:selected_user_profile' slug=selected_quest.slug username=user.username %}">
                    <div class='col-xs-6 col-sm-6 col-md-2'>
                        <div class='thumbnail interested-each-user'>
                            {% with pro_img=user.profile_thumbnail %}
                                <img class='image-size image-margin-top' src="{{ pro_img.image_url }}" alt='profile-image'>
                            {% endwith %}
                            <div class='caption justify-center'>
                                <h5>{{ user.username }}</h5>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
            {% else %}
            <div class='col-md-12'>
                <p>Not Accessible</p>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

{% block footer %}
{% endblock footer %}

{% block javascript %}
    {{ block.super }}
{% endblock javascript %}

templates/quests/quest_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}
{% load humanize %}

{% block title %}
    {{ block.super }} - {{ quest.title }}   
{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    <link rel='stylesheet' type='text/css' href="{% static 'css/quest_detail.css' %}">
{% endblock stylesheets %}

{% block content %}
<div class='container'>
    <div class="row">
        {% for message in messages %}
            {% if 'diffuse-message' in message.tags %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
            {% endif %}
        {% endfor %}
        <div class='col-md-3 justify-center'>
            <div class='thumbnail'>
                    <a href="{% url 'quests:selected_user_list' quest.user.username %}"> 
                        <img class='image-size image-margin-top' src="{{ profile_picture.image_url }}" alt='profile-image'>
                    </a>
                <div class='caption'>
                    <h4>{{ quest.user.username }}</h4>
                </div>
            </div>
            <div class='thumbnail location-thumbnail'>
                <h5>Location</h5>
                <hr/>
                {% if quest.location %}
                    <a href='https://www.google.com/maps/?q={{ quest.location }}'>
                    <div class='location'>
                        <p class='address'>{{ quest.location|title }}</p>
                {% else %}
                    <div class='location'>
                        <p class='address'>N/A</p>
                {% endif %}
                    </div>
                </a>
            </div>
            <p class='address-notice'>Click the address to see the location</p>
            {% if request.user.is_authenticated %}
                {% if request.user == quest.user %}
                    <div id='diffuse-list'>
                        <a class='btn btn-primary btn-block' href="{% url 'quests:interested_users' quest.slug %}">
                            Defuse List    
                        </a>
                    </div>
                    <button class="btn btn-block btn-success option-buttons" type="button" 
                    data-toggle="collapse" data-target="#collapseExample" 
                    aria-expanded="false" aria-controls="collapseExample">
                        Options
                    </button>
                    <div class="collapse" id="collapseExample">
                        <div class="well">
                            <a class='btn btn-primary btn-block collapse-buttons' type='button'
                            href="{% url 'quests:edit_quest_images' object.slug %}"> 
                                Add / Delete Photos
                            </a>
                            <a class='btn btn-warning btn-block collapse-buttons' type='button'
                            href="{% url 'quests:update_quest' object.slug %}">
                                Modify Quest
                            </a>
                            <a class='btn btn-danger btn-block collapse-buttons-last'
                            href="{% url 'quests:delete_quest' object.slug %}"> 
                                Self-destruct
                            </a>
                        </div>
                    </div>
                {% else %}
                    <div class='diffuse-button'>
                        {% if request.user in interested_users_list %}
                            <a class='btn btn-block btn-danger'
                            href="{% url 'quests:diffuse' object.slug %}">
                            Retract
                        {% else %}
                            <a class='btn btn-block btn-primary'
                            href="{% url 'quests:diffuse' object.slug %}">
                                Defuse
                        {% endif %}
                        </a>
                    </div>
                {% endif %}
            {% else %}
            <div class='diffuse-button'>
                <a class='btn btn-block btn-success'
                href="{% url 'account_signup' %}">
                    Defuse
                </a>
            </div>
            {% endif %}
        </div>
        <div class='col-md-9'>
            <div class='thumbnail quest-detail-page'>
                <p class='bold-title h4'>"{{ quest.title|title }}"</p>
                <p class='description-text'>{{ quest.description|capfirst|linebreaks|urlize }}</p>
                {% if quest.reward_type == "MonetaryH" %}
                    <p class='justify-right reward-text'><span class='dollar-color'>$</span> {{ quest.mon_reward }} / Hour</p>
                {% elif quest.reward_type == "MonetaryF" %}
                    <p class='justify-right reward-text'><span class='dollar-color'>$</span> {{ quest.mon_reward }} / Flat</p>
                {% elif quest.reward_type == "Non-monetary" %}
                    <p class='justify-right reward-text'>{{ quest.non_mon_rewards }}</p>
                {% else %}
                    <p class='justify-right reward-text'>{{ quest.reward_type }}</p>
                {% endif %}
                <p>{{ quest.rewards }}</p>
                <p class='justify-right explosion-text'>Explode in {{ quest.explosion_datetime|timeuntil }}</p> 
            </div>
            {% if uploaded_images %}
            <div id="carousel-example-generic" class="carousel slide" data-interval='false' data-ride="carousel">
                <div class="carousel-inner" role="listbox">
                    {% for upload in uploaded_images %}
                        {% if forloop.first %}
                            <div class="item active">
                        {% else %}
                            <div class="item">
                        {% endif %}
                                <img src="{{ upload.quest_images.url }}" alt="...">
                            </div>
                    {% endfor %}
                </div>
                
                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
    {{ block.super }}
{% endblock footer %}

{% block javascript %}
    {{ block.super }}
{% endblock javascript %}

templates/quests/selected_user_profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} 
{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    <link rel='stylesheet' type='text/css' href="{% static 'css/user_profile.css' %}">
{% endblock stylesheets %}

{% block content %}
    <div class='container'>
        <div class='row'>
            <div class='col-md-offset-2 col-md-8 main-profile-page'>
                <div class='row'>
                    <div class='col-md-4'>
                        <div class='profile-img'>
                            <img class='image-size image-margin-top img-circle' src="{{ profile_img.image_url }}" alt='profile-image'>
                        </div>
                        <div class='basic-info-field justify-center'>
                            <p>{{ user.username }}</p>
                            <p>{{ email.email }}</p>
                        </div>
                        <div>
                            <a class='btn btn-block btn-primary' href="{% url 'quests:send_message' quest.slug user.username %}">Send a Message</a>
                        </div>
                    </div>
                    <div class='col-md-8 experience-field'>
                        <div class='row'>
                            <div class='col-md-12'>
                                <h4>Experience</h4>
                            </div>
                            {% for experience in experiences %}
                                <div class='col-md-12'>    
                                    <div class='thumbnail each-experience-field'>
                                        <p class='each-title'>{{ experience.title|title }}</p>
                                        <p class='company-name'>{{ experience.company }}</p>
                                        <p>{{ experience.description }}</p>
                                        <p class='duration justify-right'>{{ experience.started_date }} - {{ experience.end_date }}</p>
                                    </div>
                                </div>
                            {% empty %}
                                <div class='col-md-12'>
                                    <div class='thumbnail each-experience-field'>
                                        <p>No Experience Listed</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}
{% endblock footer %}

{% block javascript %}
    {{ block.super }}
{% endblock javascript %}