explodingquests/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from django.views.generic import TemplateView
from profiles.views import ContactUsFormView
from quests.views import (
    QuestListView,
    get_user_settings,
    password_change_page_view,
    account_inactive_redux,
    email_verification_redux,
)


urlpatterns = [
    url(r'^$', QuestListView.as_view(), name='homepage'),
    url(r'^quests/', include('quests.urls', namespace='quests')),
    url(r'^accounts/password/change/$', password_change_page_view, name='account_change_password'),
    url(r'^accounts/inactive/$', account_inactive_redux, name='account_inactive'),
    url(r'^accounts/confirm-email/$', email_verification_redux, name='account_email_verification_sent'),
    url(r'^accounts/settings/$', get_user_settings, name='user_settings'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^dashboards/', include('profiles.urls', namespace='dashboard')),
    url(r'^contact/$', ContactUsFormView.as_view(), name='contact_us'),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

quests/urls.py
from django.conf.urls import url

from .views import (
    QuestListView, QuestDetailView,
    CreateQuest, DeleteQuestView,
    UpdateQuestView,
    get_selected_user_list,
    edit_quest_images,
    delete_quest_images,
    interested_users_list,
    get_selected_user_profile,
    MessageCreateView,
    DiffuseToggle,
)

urlpatterns = [
    # url(r'^$', QuestListView.as_view(), name='homepage'),
    url(r'^create/$', CreateQuest.as_view(), name='create_quest'),
    url(r'^(?P<slug>[\w-]+)/$', QuestDetailView.as_view(), name='quest_detail'),
    url(r'^(?P<slug>[\w-]+)/images/$', edit_quest_images, name='edit_quest_images'),
    url(r'^delete/(?P<id>[\w-]+)/$', delete_quest_images, name='delete_quest_images'),
    url(r'^(?P<slug>[\w-]+)/defuse/$', DiffuseToggle.as_view(), name='diffuse'),
    url(r'^(?P<slug>[\w-]+)/interested/$', interested_users_list, name='interested_users'),
    url(r'^(?P<slug>[\w-]+)/interested/(?P<username>[a-zA-Z0-9]+)/$',
        get_selected_user_profile, name='selected_user_profile'),
    url(r'^(?P<slug>[\w-]+)/interested/(?P<username>[a-zA-Z0-9]+)/send_msg/$',
        MessageCreateView.as_view(), name='send_message'),
    url(r'^(?P<slug>[\w-]+)/update/$', UpdateQuestView.as_view(), name='update_quest'),
    url(r'^(?P<slug>[\w-]+)/delete/$', DeleteQuestView.as_view(), name='delete_quest'),
    url(r'^(?P<username>[a-zA-Z0-9]+)/quest_list/$', get_selected_user_list, name='selected_user_list'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap %}
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}ExplodingQuest{% endblock title %}
        </title>
        {% block stylesheets %}
            <!-- Bootstrap -->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
            <link rel="shortcut icon" type="image/png" href="{% static 'image/favicon.png' %}">
            <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
        {% endblock stylesheets %}
    </head>
    <body>
        <!-- Navigation -->
        <nav class='navbar navbar-default navbar-fixed-top'>
            <div class='container'>
                <div class='navbar-header'>
                    <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class='navbar-brand' href="{% url 'homepage' %}">
                         <span class='explosion_color'>Exploding</span><span class='quest'>Quest</span> 
                    </a>
                </div>

                <div id='navbar' class='collapse navbar-collapse'>
                    <form class="navbar-form navbar-left">
                        <div class="input-group">
                            <form method='GET' action="{% url 'homepage' %}", id="general-searchform">
                                <input type="text" class="form-control" id='navbar-searchform'
                                name = "q" value="{{ request.GET.q }}" placeholder="Search for...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <span class='glyphicon glyphicon-search'></span>
                                    </button>
                                </span>
                            </form>
                        </div>
                    </form>
                    <ul class='nav navbar-nav navbar-right'>
                        {% with current_user=request.user %}
                        {% if current_user.is_authenticated %}
                        <li>
                            <a href="{% url 'quests:create_quest' %}">
                                <span class="glyphicon glyphicon-pencil"></span>
                                <span class='dropdown-menu-icon'>Post a Quest</span>
                            </a>
                        </li>
                        <li class='dropdown'>
                            <a class="dropdown-toggle" role='button'
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class='glyphicon glyphicon-user'></span>
                                <span class='dropdown-menu-icon'>My Account</span>
                                <span class="caret"></span> 
                            </a>
                            <ul class="dropdown-menu">
                                <li class='dropdown-menu-options'>
                                    <a href="{% url 'dashboard:user_dashboard' %}">
                                        <span class='glyphicon glyphicon-dashboard'></span>
                                        <span class='dropdown-menu-icon'>Dashboard</span>
                                    </a>
                                </li>
                                <li class='dropdown-menu-options'>
                                    <a href="{% url 'user_settings' %}">
                                        <span class='glyphicon glyphicon-cog'></span>
                                        <span class='dropdown-menu-icon'>Settings</span>
                                    </a>
                                </li>
                                <hr/>
                                <li class='dropdown-menu-options'>
                                    <a data-toggle="modal" data-target="#logOutModal"> 
                                        <span class='glyphicon glyphicon-log-out'></span> 
                                        <span class='dropdown-menu-icon'>Logout</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        {% else %}
                        <li>   
                            <a href="{% url 'account_login' %}">Login</a> 
                        </li>
                        <li>
                            <a href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                        {% endif %}
                        {% endwith %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% with current_user=request.user %}
            {% if current_user.is_authenticated %}
                {% include 'modal.html' with title="Logout?" button="Confirm" id="logOutModal" label="logOutLabel" %} 
            {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock content %}

        {% block footer %}
            <footer class='footer'>
                <div class='container'>
                    <p class='text-muted'>
                        &copy; 2017 ExplodingQuests, Inc.
                        | <a href="{% url 'contact_us' %}" class='contact'>Contact</a>
                    </p>    
                </div>    
            </footer> 
        {% endblock footer %}

        {% block javascript %}
            <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <!-- Include all compiled plugins (below), or include individual files as needed -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script> 

        {% endblock javascript %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block title %}
    {{ block.super }}
{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
{% endblock stylesheets %}

{% block content %}
    <div class='jumbotron'>
         <div class='container'>
            <p class='h1'>The world is full of quests</p>
            <p class='lead'>Get them before they explode!</p>
         </div>
    </div>
    <div class='container'>
        <div class='row'>
            {% for quest in quest_list %}
            <a href="{{ quest.get_absolute_url }}">
                <div class='col-md-3 justify-center quest-list'>
                    <div class='thumbnail quest-thumbnail'>
                        <h5 class='justify-left quest-title'>{{ quest.title|title|truncatewords:5 }}</h5>
                        {% if quest.uploads.first %}
                            <img src="{{ quest.uploads.first.quest_images.url }}"/>
                        {% else %}
                            {% with pro_img=quest.user.profile_thumbnail %}
                                <img class='image-size' src="{{ pro_img.image_url }}"/>
                            {% endwith %} 
                        {% endif %} 
                        <div class='caption main-page-caption'>
                            <p>{{ quest.description|truncatewords:10 }}</p>
                            {% if quest.reward_type == "MonetaryH" %}
                                <p class='display-reward'><span class='dollar-color'>$</span> {{ quest.mon_reward }} / hour</p>
                            {% elif quest.reward_type == "MonetaryF" %}
                                <p class='display-reward'><span class='dollar-color'>$</span> {{ quest.mon_reward }} flat</p>
                            {% elif quest.reward_type == "Non-monetary" %}
                                <p class='display-reward'>{{ quest.non_mon_rewards }}</p>
                            {% else %}
                                <p class='display-reward'>{{ quest.reward_type }}</p>
                            {% endif %}
                        </div>
                        <p class='red-fire justify-right'>
                            {{ quest.explosion_datetime|timeuntil }} left
                        </p>
                    </div>
                </div>
            </a>
            {% empty %}
            <div class='col-md-12 justify-center'>
                <p>No Quest Found</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block footer %}
    {{ block.super }}
{% endblock footer %}

{% block javascript %}
    {{ block.super }}
{% endblock javascript %}

templates/modal.html
<div class="modal fade" id="{{ id }}" tabindex="-1" role="dialog" aria-labelledby="{{ label }}">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content justify-center">
            <div class="modal-header title-left-padding">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title" id="{{ label }}">{{ title }}</h5>
            </div>
            <div class="modal-footer"> 
                <form method="post" action="{% url 'account_logout' %}">
                    {% csrf_token %}
                    {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                    {% endif %}
                <button class='btn btn-danger btn-block btn-margin' type="submit">{{ button }}</button>
                </form>
            </div> 
        </div>
    </div>
</div>