explodingquests/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from django.views.generic import TemplateView
from profiles.views import ContactUsFormView
from quests.views import (
    QuestListView,
    get_user_settings,
    password_change_page_view,
    account_inactive_redux,
    email_verification_redux,
)


urlpatterns = [
    url(r'^$', QuestListView.as_view(), name='homepage'),
    url(r'^quests/', include('quests.urls', namespace='quests')),
    url(r'^accounts/password/change/$', password_change_page_view, name='account_change_password'),
    url(r'^accounts/inactive/$', account_inactive_redux, name='account_inactive'),
    url(r'^accounts/confirm-email/$', email_verification_redux, name='account_email_verification_sent'),
    url(r'^accounts/settings/$', get_user_settings, name='user_settings'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^dashboards/', include('profiles.urls', namespace='dashboard')),
    url(r'^contact/$', ContactUsFormView.as_view(), name='contact_us'),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

profiles/urls.py
from django.conf.urls import url

from .views import (
    WorkExperienceCreateView,
    WorkExperienceUpdateView,
    WorkExperienceDeleteView,
    user_quest_list_view,
    user_dashboard,
    profile_list_view,
    MessageInboxView,
    MessageDetailView,
    MessageDelete,
    SentPageMessageReply,
    InterestedPageMessageReply,
)

urlpatterns = [
    url(r'^$', user_dashboard, name='user_dashboard'),
    url(r'^my_profile/$', profile_list_view, name='my_profile'),
    url(r'^my_profile/add_experience/$',
        WorkExperienceCreateView.as_view(), name='work_experience'),
    url(r'^my_profile/(?P<pk>[\w-]+)/update/$',
        WorkExperienceUpdateView.as_view(), name='update_experience'),
    url(r'^my_profile/(?P<pk>[\w-]+)/delete/$',
        WorkExperienceDeleteView.as_view(), name='delete_experience'),
    url(r'^quest_list/$', user_quest_list_view, name='user_quest_list'),
    url(r'^message_inbox/$', MessageInboxView.as_view(), name='message_inbox'),
    url(r'^message_inbox/(?P<pk>[\w-]+)/$',
        MessageDetailView.as_view(), name='message_detail'),
    url(r'^message_inbox/(?P<pk>[\w-]+)/delete/$',
        MessageDelete.as_view(), name='message_to_trash'),
    url(r'^message_inbox/(?P<pk>[\w-]+)/reply/$',
        SentPageMessageReply.as_view(),
        name='message_reply'),
    url(r'^message_inbox/(?P<pk>[\w-]+)/send/$',
        InterestedPageMessageReply.as_view(),
        name='interested_message_reply'),
]

quests/urls.py
from django.conf.urls import url

from .views import (
    QuestListView, QuestDetailView,
    CreateQuest, DeleteQuestView,
    UpdateQuestView,
    get_selected_user_list,
    edit_quest_images,
    delete_quest_images,
    interested_users_list,
    get_selected_user_profile,
    MessageCreateView,
    DiffuseToggle,
)

urlpatterns = [
    # url(r'^$', QuestListView.as_view(), name='homepage'),
    url(r'^create/$', CreateQuest.as_view(), name='create_quest'),
    url(r'^(?P<slug>[\w-]+)/$', QuestDetailView.as_view(), name='quest_detail'),
    url(r'^(?P<slug>[\w-]+)/images/$', edit_quest_images, name='edit_quest_images'),
    url(r'^delete/(?P<id>[\w-]+)/$', delete_quest_images, name='delete_quest_images'),
    url(r'^(?P<slug>[\w-]+)/defuse/$', DiffuseToggle.as_view(), name='diffuse'),
    url(r'^(?P<slug>[\w-]+)/interested/$', interested_users_list, name='interested_users'),
    url(r'^(?P<slug>[\w-]+)/interested/(?P<username>[a-zA-Z0-9]+)/$',
        get_selected_user_profile, name='selected_user_profile'),
    url(r'^(?P<slug>[\w-]+)/interested/(?P<username>[a-zA-Z0-9]+)/send_msg/$',
        MessageCreateView.as_view(), name='send_message'),
    url(r'^(?P<slug>[\w-]+)/update/$', UpdateQuestView.as_view(), name='update_quest'),
    url(r'^(?P<slug>[\w-]+)/delete/$', DeleteQuestView.as_view(), name='delete_quest'),
    url(r'^(?P<username>[a-zA-Z0-9]+)/quest_list/$', get_selected_user_list, name='selected_user_list'),
]

profiles/forms.py
from django import forms

from .models import (
    WorkExperience, Education,
    DefuseMessage, ContactUs)


class WorkExperienceForm(forms.ModelForm):

    class Meta:
        model = WorkExperience
        fields = (
            'company',
            'title',
            'description',
            'started_date',
            'end_date',
        )
        widgets = {
            'title': forms.TextInput(
                attrs={
                    "class": "form-control",
                    'placeholder': "Title",
                     }),
            'company': forms.TextInput(
                attrs={
                    "class": "form-control",
                    'placeholder': "Company",
                     }),
            'description': forms.Textarea(
                attrs={
                    "class": "form-control",
                    'placeholder': "Description",
                     }),
            'started_date': forms.DateInput(
                attrs={
                    "class": "form-control",
                    'placeholder': "From",
                    "readonly": "readonly",
                     }),
            'end_date': forms.DateInput(
                attrs={
                    "class": "form-control",
                    'placeholder': "To",
                    "readonly": "readonly",
                     }),
        }


class EducationForm(forms.ModelForm): 
    
    class Meta:
        model = Education 
        exclude = ['user']


class SendMessageForm(forms.ModelForm):

    class Meta:
        model = DefuseMessage
        fields = (
            'subject',
            'content',
        )
        labels = {
            'subject': '',
            'content': '',
        }
        widgets = {
            'subject': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Subject',
                }),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Content',
                }),
        }


class ReplyForm(forms.ModelForm):

    class Meta:
        model = DefuseMessage
        fields = (
            'content',
        )
        labels = {
            'content': '',
        }
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 6,
                    'onfocus':"this.placeholder = ''",
                    'placeholder': 'Click here to reply',
                }),
        }


class ContactUsForm(forms.ModelForm):

    class Meta:
        model = ContactUs
        fields = (
            'contact_info',
            'content',
        )
        widgets = {
            'contact_info': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Best way to reach you',
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'What do you need help with?',
                }
            ),
        }

profiles/views.py
from allauth.account.models import EmailAddress

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse_lazy, reverse
from django.db.models import Q 
from django.shortcuts import render, get_list_or_404, get_object_or_404, Http404
from django.views.generic import (
    CreateView, ListView, 
    UpdateView, DeleteView, 
    DetailView, RedirectView,)
from django.utils import timezone

from quests.models import UserProfileImage, Quest

from .models import (
    Education, WorkExperience,
    DefuseMessage, ContactUs)
from .forms import (
    EducationForm, WorkExperienceForm,
    SendMessageForm, ContactUsForm,
    ReplyForm)
from .mixins import CheckingUserPermissionMixin, UserExperiencePermissionMixin

# Create your views here.


class ContactUsFormView(CreateView):
    '''contact form'''
    model = ContactUs
    form_class = ContactUsForm
    success_url = reverse_lazy('homepage')


@login_required
def profile_list_view(request):
    """A page where users can view their own profile"""
    user = get_object_or_404(User, username=request.user.username)
    email = get_object_or_404(EmailAddress, user=user, primary=True)
    profile_img = get_object_or_404(UserProfileImage, user=user)
    experience = ''

    try:
        experience = get_list_or_404(WorkExperience, user=user)
    except:
        pass

    context = {
        'user': user,
        'email': email,
        'experiences': experience,
        'profile_img': profile_img,
    }

    return render(request, 'profiles/profile_list.html', context)


@login_required
def user_quest_list_view(request):
    """A page where users can view their collection of quests"""
    user_quest_list = ''

    try:
        user_quest_list = Quest.objects.filter(user=request.user, explosion_datetime__gte=timezone.now())
        user_quest_list_count = user_quest_list.count()
        all_quest = Quest.objects.all()
        defused_quests = all_quest.filter(interested_users=request.user)
        defused_quests_count = defused_quests.count()
    except ObjectDoesNotExist:
        msg = "No quest"
        raise ObjectDoesNotExist(msg)

    context = {
        'list': user_quest_list,
        'count': user_quest_list_count,
        'def_quests': defused_quests,
        'def_quest_count': defused_quests_count,
    }
    return render(request, 'profiles/user_quest_list.html', context)


@login_required
def user_dashboard(request):
    """User dashboard"""
    profile_pic = UserProfileImage.objects.get(user=request.user)
    received = DefuseMessage.objects.filter(
        receiver=request.user, viewed_by_receiver=False, trash_by_receiver=False).count()
    template_name = 'profiles/user_dashboard.html'
    context = {
        'profile_pic': profile_pic,
        'new': received,
    }
    return render(request, template_name, context)


class MessageInboxView(LoginRequiredMixin, ListView):
    """Message Inbox page"""
    model = DefuseMessage
    context_object_name = 'messages'
    template_name = 'profiles/inbox_pages.html'

    def get_context_data(self, *args, **kwargs):
        # for each in context['sender']:
        #     each_reply_count = each.replies.all()
        #     print(each_reply_count)
        #     count_unread = [unread for unread in each_reply_count if unread.viewed_by_receiver == False]
        #     print(len(count_unread))
        context = super().get_context_data(*args, **kwargs)
        every_message = DefuseMessage.objects.prefetch_related('replies')
        unread_count, created_unread_count = {}, {}
        context['receiver'] = every_message.filter(
            receiver=self.request.user, trash_by_receiver=False, parent__isnull=True).order_by('-send_at')
        for each in context['receiver']:
            unread_count[each.id] = each.replies.all().filter(
                receiver=self.request.user, viewed_by_receiver=False).count()
        context['unread_count'] = unread_count
        context['total_count'] = sum(unread_count.values())
        context['sender'] = every_message.filter(
            sender=self.request.user, trash_by_sender=False, parent__isnull=True).order_by('-send_at')
        for each in context['sender']:
            created_unread_count[each.id] = each.replies.all().filter(
                receiver=self.request.user, viewed_by_receiver=False).count()
        context['created_unread_count'] = created_unread_count
        context['created_unread_total_count'] = sum(created_unread_count.values())       
        return context


class MessageDetailView(LoginRequiredMixin, CheckingUserPermissionMixin, DetailView):
    """message detail"""
    template_name = 'profiles/defusemessage_detaill.html'
    model = DefuseMessage
    context_object_name = 'message'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        particular_message = get_object_or_404(DefuseMessage, pk=self.kwargs['pk'])
        context['sender_email'] = get_object_or_404(EmailAddress, user=particular_message.sender)
        context['sender_profile'] = get_object_or_404(UserProfileImage, user=particular_message.sender)
        context['receiver_profile'] = get_object_or_404(UserProfileImage, user=particular_message.receiver)
        context['quest'] = get_object_or_404(Quest, slug=particular_message.related_quest.slug)
        context['children'] = particular_message.replies.all().order_by('send_at')
        context['reply_form'] = ReplyForm()
        context['create_url'] = reverse('dashboard:message_reply', kwargs={'pk': particular_message.pk})
        context['interested_url'] = reverse('dashboard:interested_message_reply', kwargs={'pk': particular_message.pk})
        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        current_user = get_object_or_404(User, username=self.request.user.username)
        particular_message = get_object_or_404(DefuseMessage, pk=self.kwargs['pk'])
        replies = DefuseMessage.objects.filter(parent=particular_message)
        if self.object.receiver == current_user:
            self.object.read_by_receiver()
            print(self.object)
        for reply in replies:
            if reply.receiver == current_user:
                reply.read_by_receiver()
        return self.render_to_response(context)


class MessageDelete(LoginRequiredMixin, CheckingUserPermissionMixin, RedirectView):
    """delete message button"""
    def get_redirect_url(self, *args, **kwargs):
        msg_pk = self.kwargs.get('pk')
        msg = get_object_or_404(DefuseMessage, pk=msg_pk)
        msg_sender = get_object_or_404(User, username=msg.sender.username)
        msg_receiver = get_object_or_404(User, username=msg.receiver.username)
        url_ = reverse_lazy("dashboard:message_inbox")
        user = self.request.user
        if user.is_authenticated():
            if msg_sender == user:
                if not msg.trash_by_sender:
                    msg.trash_by_sender = True
                    msg.save()
            elif msg.receiver == user:
                if not msg.trash_by_receiver:
                    msg.trash_by_receiver = True
                    msg.save()
            else:
                Http404
        return url_


class SentPageMessageReply(LoginRequiredMixin, CreateView):
    """Reply to a specific message"""
    # can't think straight today just gonna be lazy and not think too much about it
    form_class = ReplyForm
    # success_url = reverse_lazy("dashboard:message_detail", kwargs={'pk': })

    def form_valid(self, form):
        particular_message = get_object_or_404(DefuseMessage, pk=self.kwargs['pk'])
        receiver = get_object_or_404(User, username=particular_message.receiver.username)
        quest = get_object_or_404(Quest, slug=particular_message.related_quest.slug)
        self.object = form.save(commit=False)
        self.object.sender = self.request.user
        self.object.receiver = receiver
        self.object.related_quest = quest
        if particular_message.parent:
            self.object.parent = particular_message.parent
        else:
            self.object.parent = particular_message
        self.object.subject = "Re: " + particular_message.subject
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        if 'pk' in self.kwargs:
            pk = self.kwargs['pk']
        return reverse_lazy('dashboard:message_detail', kwargs={'pk': pk})


class InterestedPageMessageReply(LoginRequiredMixin, CreateView):
    """Reply to a specific message"""
    form_class = ReplyForm

    def form_valid(self, form):
        particular_message = get_object_or_404(DefuseMessage, pk=self.kwargs['pk'])
        receiver = get_object_or_404(User, username=particular_message.sender.username)
        quest = get_object_or_404(Quest, slug=particular_message.related_quest.slug)
        self.object = form.save(commit=False)
        self.object.sender = self.request.user
        self.object.receiver = receiver
        self.object.related_quest = quest
        if particular_message.parent:
            self.object.parent = particular_message.parent
        else:
            self.object.parent = particular_message
        self.object.subject = "Re: " + particular_message.subject
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        if 'pk' in self.kwargs:
            pk = self.kwargs['pk']
        return reverse_lazy('dashboard:message_detail', kwargs={'pk': pk})


class WorkExperienceCreateView(LoginRequiredMixin, CreateView):

templates/profiles/contactus_form.html
{% extends "base.html" %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link rel='stylesheet' type='text/css' href="{% static 'css/experience_form.css' %}">
{% endblock stylesheets %}

{% block content %}
    <div class='container'>
        <div class='row'>
            <div class='col-md-offset-2 col-md-8 experience-form-page'>
                <div class='row'>
                    <form method='POST' action='' id='contact-form'>
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <div class='col-md-12'>
                                {{ field }} 
                            </div>
                        {% endfor %}
                        <div class='col-md-offset-10 col-md-2'>
                            <input class='btn btn-block btn-primary' type='submit' value='Submit'>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    {{ block.super }}
{% endblock footer %}

{% block javascript %}
    {{ block.super }}
    <script>
        $("#contact-form").submit(function( event ) {
            alert('We will get in touch with you shortly.');
        });
    </script>
{% endblock javascript %}

templates/profiles/defusemessage_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - Inbox
{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    <link rel='stylesheet' type='text/css' href="{% static 'css/msg_detail.css' %}">
{% endblock stylesheets %}

{% block content %}
<div class="container">
    <div class='row msg-detail-nav-row'>
        <div class='col-md-offset-2 col-md-8 nav-border top-menu'>
            <div class='row'>
                <div class='col-xs-9 col-sm-9 col-md-9'>
                    <p class='quest-of-interest'>
                        <a class='quest-link' href="{% url 'quests:quest_detail' slug=quest.slug %}">
                            {{ message.related_quest|title }}
                        </a>
                    </p>
                </div>
                <div class='col-xs-3 col-sm-3 col-md-offset-1 col-md-2'>
                    <a href="{% url 'dashboard:message_to_trash' pk=message.pk %}" class='btn btn-default btn-block'>
                        <span class='glyphicon glyphicon-trash'></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class='row'>
        <div class='col-md-offset-2 col-md-6'>
            <div class='message-detail-page'>
                {% if sender_email.user == request.user %}
                    <p class='msg-sender'>Me 
                        <span class='to-whom'>to {{ message.receiver }}</span>
                    </p>
                {% else %}
                    <div class='sender-and-quest'>
                        <img src="{{ sender_profile.image_url }}" class='img-circle sender-profile-img' />
                        <p class='msg-sender'>{{ sender_email.user }}</p>
                        <p class='creator-of'>- Quest Creater of 
                            <a class='quest-link' href="{% url 'quests:quest_detail' slug=quest.slug %}">
                                "{{ message.related_quest|title }}"
                            </a>
                        </p>
                    </div>
                    <p class='msg-sent-at'>{{ message.send_at|date:"m/d/y G:i" }}</p>
                {% endif %}
                <p class='msg-content'>{{ message.content|linebreaks|urlize }}</p>
            </div>
            <div class='date-at-the-bottom justify-right'>
                <p class='msg-sent-at'>{{ message.send_at|date:"m/d/y G:i" }}</p>
            </div>
        </div>
    </div>
    <div class='row'>
        <div class='col-md-offset-2 col-md-6'>
            {% for child in children %}
                <div class='message-detail-page'>
                    {% if sender_email.user == request.user %}
                        <p class='msg-sender'>Me 
                            <span class='to-whom'>to {{ child.receiver }}</span>
                        </p>
                    {% endif %}
                    <p class='msg-content'>{{ child.content|linebreaks|urlize }}</p>
                </div>
                <div class='date-at-the-bottom justify-right'>
                    <p class='msg-sent-at'>{{ child.send_at|date:"m/d/y G:i" }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
    <hr/>
    <div class='row'>
        <div class='col-md-offset-2 col-md-8'>
            {% include "profiles/sent_reply.html" with form=reply_form action_url=create_url %}
        </div>
    </div>
</div>
{% endblock content %}

{% block footer %}
    {{ block.super }}
{% endblock footer %}

{% block javascript %}
    {{ block.super }}
    <script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
    </script>
{% endblock javascript %}

templates/profiles/defusemessage_detaill.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - Inbox
{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    <link rel='stylesheet' type='text/css' href="{% static 'css/msg_detail.css' %}">
{% endblock stylesheets %}

{% block content %}
<div class="container">
    <div class='row msg-detail-nav-row'>
            <div class='col-xs-offset-9 col-xs-3 col-sm-offset-9 col-sm-3 col-md-offset-9 col-md-1'>
                <a href="{% url 'dashboard:message_to_trash' pk=message.pk %}" class='btn btn-default btn-block'>
                    <span class='glyphicon glyphicon-trash'></span>
                </a>
            </div>
    </div>
    <div class='row'>
        <div class='col-md-offset-2 col-md-8'>
            <div class='message-detail-page'>
                <p class='msg-subject'>{{ message.subject|title }}</p>
                <!-- message sender is the current user -->
                <!-- created box -->
                {% if sender_email.user == request.user %}
                    <p class='msg-sender'>Me 
                        <span class='to-whom'>to {{ message.receiver }}</span>
                    </p>
                    <p class='quest-of-interest'>regarding  
                        <a class='quest-link' href="{% url 'quests:quest_detail' slug=quest.slug %}">
                            "{{ message.related_quest|title }}"
                        </a>
                    </p>
                {% else %}
                    <!-- message receiver is the current user -->
                    <!-- inbox page -->
                    <div class='sender-and-quest'>
                        <img src="{{ sender_profile.image_url }}" class='img-circle sender-profile-img' />
                        <p class='msg-sender'>{{ sender_email.user }}</p>
                        <p class='creator-of'>- Quest Creater of 
                            <a class='quest-link' href="{% url 'quests:quest_detail' slug=quest.slug %}">
                                "{{ message.related_quest|title }}"
                            </a>
                        </p>
                    </div>
                    <p class='msg-sent-at'>{{ message.send_at|date:"m/d/y G:i" }}</p>
                {% endif %}
                <p class='msg-content'>{{ message.content|linebreaks|urlize }}</p>
            </div>
            <div class='date-at-the-bottom justify-right'>
                <p class='msg-sent-at'>{{ message.send_at|date:"m/d/y G:i" }}</p>
            </div>
        </div>
    </div>
    <div class='row'>
        <div class='col-md-offset-2 col-md-8'>
            {% for child in children %}
                <div class='message-detail-page reply-list'>
                    {% if sender_email.user == request.user %}
                        <!-- reply reciepient is the current user -->
                        <!-- my 'created_page'-->
                        {% if child.sender != request.user %}
                            <img src="{{ receiver_profile.image_url }}"
                            class='img-circle reply-profile-img' />
                            <p class='reply-sender-name'>{{ child.sender }}</p>
                        {% endif %}
                    {% elif sender_email.user != request.user %}
                        <!-- my inbox's initial sender is a quest creator -->
                        {% if child.sender != request.user %}
                            <!-- if i am not the one who replied -->
                            <img src="{{ sender_profile.image_url }}"
                            class='img-circle reply-profile-img' />
                            <p class='reply-sender-name'>{{ child.sender }}</p>
                        {% endif %} 
                    {% endif %}
                </div>
                {% if child.sender == request.user %}
                    <div class='message-detail-page reply-content'>
                {% else %}
                    <div class='message-detail-page reply-content interested-person-reply'>
                {% endif %}
                    <p class='msg-content'>{{ child.content|linebreaks|urlize }}</p>
                </div>
                <div class='date-at-the-bottom justify-right'>
                    <p class='msg-sent-at'>{{ child.send_at|date:"m/d/y G:i" }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
    <hr/>
    <div class='row'>
        {% if sender_email.user == request.user %}
            <!-- if the sender of the current message is the currently loggined in user-->
            <div class='col-md-offset-2 col-md-8'>
                {% include "profiles/sent_reply.html" with form=reply_form action_url=create_url %}
            </div>
        {% else %}
            <div class='col-md-offset-2 col-md-8'>
                {% include "profiles/sent_reply.html" with form=reply_form action_url=interested_url %}
            </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

{% block footer %}
    {{ block.super }}
{% endblock footer %}

{% block javascript %}
    {{ block.super }}
    <script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
    </script>
{% endblock javascript %}

templates/profiles/profile_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - My Profile
{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    <link rel='stylesheet' type='text/css' href="{% static 'css/user_profile.css' %}">
{% endblock stylesheets %}

{% block content %}
    <div class='container'>
        <div class='row'>
            <div class='col-md-offset-2 col-md-8 main-profile-page'>
                <div class='row'>
                    <div class='col-md-4'>
                        <div class='profile-img'>
                            <img class='image-size image-margin-top img-circle' src="{{ profile_img.image_url }}" alt='profile-image'>
                        </div>
                        <div class='basic-info-field justify-center'>
                            {% if profile_img.preferred_name %}
                                <p>{{ profile_img.preferred_name }}</p>
                            {% else %}
                                <p>{{ user.username }}</p>
                            {% endif %}
                        </div>
                        <a href="{% url 'dashboard:work_experience' %}" class='btn btn-block btn-primary'>
                            Add Experience
                        </a>
                    </div>
                    <div class='col-md-8 experience-field'>
                        <div class='row'>
                            <div class='col-md-12'>
                                <h4>Experience</h4>
                            </div>
                            {% for experience in experiences %}
                                <div class='col-md-12'>    
                                    <div class='thumbnail each-experience-field'>
                                        <p class='each-title'>{{ experience.title|title }}
                                            <a class='glyphicon glyphicon-edit' 
                                            href="{% url 'dashboard:update_experience' experience.pk %}"
                                            data-toggle="tooltip" data-placement="right" title="Edit"></a>
                                            <a class='glyphicon glyphicon-remove red-fire' 
                                            href="{% url 'dashboard:delete_experience' experience.pk %}"
                                            data-toggle="tooltip" data-placement="right" title="Delete"></a> 
                                        </p>
                                        <p class='company-name'>{{ experience.company }}</p>
                                        <p>{{ experience.description }}</p>
                                        <p class='duration justify-right'>{{ experience.started_date }} - {{ experience.end_date }}</p>
                                    </div>
                                </div>
                            {% empty %}
                                <div class='col-md-12'>
                                    <div class='thumbnail each-experience-field'>
                                        <p>No Experience Listed</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    {{ block.super }}
{% endblock footer %}

{% block javascript %}
    {{ block.super }}
    <script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
    </script>
{% endblock javascript %}

templates/profiles/sent_reply.html
<form method="POST" action="{% if action_url %}{{ action_url }}{% endif %}">
    {% csrf_token %}
    {{ form }}
    <div class='send-reply justify-right'>
        <input class='btn btn-primary' type='submit' value='send'>
    </div>
</form>